// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARuQZAqcni_JRAETeC4KLCaZcBciRZ91Q',
    appId: '1:552157623076:web:e68c0abf6dc292e1bab9b1',
    messagingSenderId: '552157623076',
    projectId: 'flutternotes-a19b0',
    authDomain: 'flutternotes-a19b0.firebaseapp.com',
    databaseURL: 'https://flutternotes-a19b0-default-rtdb.firebaseio.com',
    storageBucket: 'flutternotes-a19b0.appspot.com',
    measurementId: 'G-PM53KMTLCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5BoT82zc1oNxJThxbfsS6oS1qbuPGX0c',
    appId: '1:552157623076:android:51512f9eb5be96bdbab9b1',
    messagingSenderId: '552157623076',
    projectId: 'flutternotes-a19b0',
    databaseURL: 'https://flutternotes-a19b0-default-rtdb.firebaseio.com',
    storageBucket: 'flutternotes-a19b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOs0j0PUurIpyLGGVD69siCLSVZOh7XIM',
    appId: '1:552157623076:ios:aa307daaf7d1d8aabab9b1',
    messagingSenderId: '552157623076',
    projectId: 'flutternotes-a19b0',
    databaseURL: 'https://flutternotes-a19b0-default-rtdb.firebaseio.com',
    storageBucket: 'flutternotes-a19b0.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOs0j0PUurIpyLGGVD69siCLSVZOh7XIM',
    appId: '1:552157623076:ios:7fa73a78f7990945bab9b1',
    messagingSenderId: '552157623076',
    projectId: 'flutternotes-a19b0',
    databaseURL: 'https://flutternotes-a19b0-default-rtdb.firebaseio.com',
    storageBucket: 'flutternotes-a19b0.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
